version: '3.1'

services:
    db:
        image: mysql
        restart: always
        environment:
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
        ports:
            - '${DB_PORT}:${DB_PORT}'

    adminer:
        image: adminer
        restart: always
        ports:
            - '8080:8080'
